import {
  futbolka1,
  futbolka2,
  futbolka3,
  futbolka4,
  futbolka5,
  futbolka6,
  futbolka7,
  kamera,
  noutbook,
  phone1,
  phone2,
  phone3,
  phone4,
  soat,
} from "../assets/images";

export const productData = [
  {
    id: 1,
    img: phone1,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "7.5",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 2,
    img: phone2,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 3,
    img: phone3,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 4,
    img: phone4,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 5,
    img: kamera,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 6,
    img: noutbook,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 7,
    img: soat,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 8,
    img: phone1,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
  {
    id: 9,
    img: phone4,
    sena: "$99.50",
    sikitka: "$1128.00",
    star: "5.9",
    info: "GoPro HERO6 4K Action Camera - Black",
  },
];

export const productShow = {
  Price: "Negotiable",
  Type: "Classic  shoes",
  Material: "Plastic material",
  Design: "Modern nice",
  Customization: "Customized logo and design custom packages",
  Protection: "Refund Policy",
  Warranty: "2 years full warranty ",
  img: [
    futbolka1,
    futbolka2,
    futbolka3,
    futbolka4,
    futbolka5,
    futbolka6,
  ],
};
